# Animals
animals_list = [
    "Dog",
    "Cat",
    "Fish",
    "Frog",
    "Bird",
    "Bear",
    "Lion",
    "Tiger",
    "Zebra",
    "Shark",
    "Whale",
    "Ant",
    "Bat",
    "Deer",
    "Fox",
    "Snake",
    "Mouse",
    "Rabbit",
    "Hamster",
    "Turtle",
    "Goat",
    "Sheep",
    "Donkey",
    "Bison",
    "Ostrich",
    "Penguin",
    "Parrot",
    "Seal",
    "Otter",
    "Rhino",
    "Hippo",
    "Panda",
    "Koala",
    "Squirrel",
    "Giraffe",
    "Gecko",
    "Coyote",
    "Yak",
    "Sloth",
    "Emu",
    "Antelope",
    "Mice",
    "Toad",
    "Eel",
    "Lark",
    "Finch",
    "Crow",
    "Dove",
    "Bee",
    "Antelope",
    "Crab",
    "Snail",
    "Clam",
    "Owl",
    "Mole",
    "Bear",
    "Wasp",
    "Bat",
    "Puffin",
    "Crow",
    "Robin",
    "Hare",
    "Tern",
    "Finch",
    "Seal",
    "Cod",
    "Gnat",
    "Ant",
    "Elk",
    "Lynx",
    "Dingo",
    "Myna",
    "Bison",
    "Koi",
    "Quail",
    "Emu",
    "Aardvark",
    "Pika",
    "Gecko",
    "Sloth",
    "Tapir",
    "Fawn",
    "Skunk",
    "Macaw",
    "Quokka",
    "Wombat",
    "Lemur",
    "Corgi",
    "Chimp",
    "Marmoset",
    "Dromedary",
    "Gopher",
    "Gibbon",
    "Vole",
    "Bongo",
    "Tamarin",
    "Raccoon",
    "Hare",
    "Moth",
    "Finch",
    "Wren",
    "Tetra",
    "Cuttle",
    "Beetle",
    "Mouse",
    "Wasp",
    "Skimmer",
    "Jay",
    "Skink",
    "Goshawk",
    "Fossa",
    "Viper",
    "Vole",
    "Gecko",
    "Cuckoo",
    "Axolotl",
    "Moth",
    "Minx",
    "Cheetah",
    "Tapir",
    "Ocelot",
    "Ferret",
    "Toad",
    "Bison",
    "Pigeon",
    "Zebra",
    "Gazelle",
    "Manatee",
    "Narwhal",
    "Manta",
    "Moray",
    "Gudgeon",
    "Prawn",
    "Shrimp",
    "Sunfish",
    "Fluke",
    "Whelk",
    "Cusk",
    "Guppy",
    "Goldfish",
    "Marlin",
    "Parrot",
    "Corvid",
    "Anole",
    "Tetra",
    "Paca",
    "Giraffe",
    "Galago",
    "Otter",
    "Viper",
    "Ocelot",
    "Rhea",
    "Quoll",
    "Tarpon",
    "Orca",
    "Aye-aye",
    "Kudu",
    "Lemur",
    "Civet",
    "Quokka",
    "Tern",
    "Puffin",
    "Vireo",
    "Cormorant",
    "Skua",
    "Booby",
    "Gallinule",
    "Skipper",
    "Lynx",
    "Ibex",
    "Tahr",
    "Wallaby",
    "Seal",
    "Gnu",
    "Maned",
    "Shrew",
    "Dhole",
    "Tortoise",
    "Cormorant",
    "Caracal",
    "Puffin",
    "Tern",
    "Kestrel",
    "Vole",
    "Seal",
    "Guppy",
    "Cusk",
    "Marlin",
    "Tarpon",
    "Harrier",
    "Trill",
    "Raptor",
    "Thrasher",
    "Wheatear",
    "Shoveler",
    "Weasel",
    "Tapir",
    "Whelk",
    "Bison",
    "Falcon"
]
# Food
food_list = [
    "Apple",
    "Banana",
    "Carrot",
    "Broccoli",
    "Tomato",
    "Onion",
    "Garlic",
    "Potato",
    "Rice",
    "Beans",
    "Lentils",
    "Peas",
    "Cheese",
    "Yogurt",
    "Milk",
    "Bread",
    "Butter",
    "Egg",
    "Chicken",
    "Beef",
    "Pork",
    "Fish",
    "Shrimp",
    "Crab",
    "Lobster",
    "Turkey",
    "Salmon",
    "Orange",
    "Grape",
    "Peach",
    "Pineapple",
    "Mango",
    "Berry",
    "Kiwi",
    "Melon",
    "Squash",
    "Spinach",
    "Kale",
    "Cabbage",
    "Zucchini",
    "Cucumber",
    "Radish",
    "Pepper",
    "Pumpkin",
    "Walnut",
    "Almond",
    "Peanut",
    "Cashew",
    "Hazelnut",
    "Flour",
    "Sugar",
    "Salt",
    "Pepper",
    "Vinegar",
    "Oil",
    "Mustard",
    "Ketchup",
    "Mayo",
    "Jelly",
    "Jam",
    "Chocolate",
    "Candy",
    "Cookie",
    "Cake",
    "Pie",
    "Doughnut",
    "Brownie",
    "Pudding",
    "Ice cream",
    "Sorbet",
    "Gelato",
    "Coffee",
    "Tea",
    "Soda",
    "Juice",
    "Water",
    "Wine",
    "Beer",
    "Chips",
    "Popcorn",
    "Noodles",
    "Pasta",
    "Pizza",
    "Taco",
    "Burrito",
    "Sandwich",
    "Wrap",
    "Salad",
    "Soup",
    "Stew",
    "Gravy",
    "Curry",
    "Quinoa",
    "Oats",
    "Granola",
    "Fudge",
    "Marshmallow",
    "Bagel",
    "Croissant",
    "Toast",
    "Frittata",
    "Omelet",
    "Scone",
    "Baguette",
    "Fruitcake",
    "Shortcake",
    "Custard",
    "Strudel",
    "Pancake",
    "Waffle",
    "Chili",
    "Ramen",
    "Falafel",
    "Jambalaya",
    "Paella",
    "Fondue",
    "Baklava",
    "Tiramisu",
    "Ratatouille",
    "Bruschetta",
    "Nachos",
    "Gazpacho",
    "Clam",
    "Fishcake",
    "Fried rice"
]
# Everyday Items
everyday_list = [
    "Phone",
    "Keys",
    "Wallet",
    "Watch",
    "Glasses",
    "Toothbrush",
    "Toothpaste",
    "Soap",
    "Shampoo",
    "Conditioner",
    "Towel",
    "Shower",
    "Clothes",
    "Shoes",
    "Food",
    "Water",
    "Coffee",
    "Tea",
    "Milk",
    "Breakfast",
    "Lunch",
    "Dinner",
    "Snacks",
    "Plate",
    "Bowl",
    "Cup",
    "Fork",
    "Spoon",
    "Knife",
    "Trash",
    "Computer",
    "Tablet",
    "Remote",
    "Light",
    "Bed",
    "Pillow",
    "Blanket",
    "Mirror",
    "Comb",
    "Hairbrush",
    "Deodorant",
    "Razor",
    "Charger",
    "Notebook",
    "Pen",
    "Paper",
    "Mail",
    "Trash can",
    "Fan",
    "Air conditioner",
    "Car",
    "Bicycle",
    "Public transport",
    "Shopping bag",
    "Mask",
    "Hand sanitizer",
    "Face wash",
    "Lotion",
    "Perfume",
    "Clippers",
    "Scissors",
    "Stapler",
    "Highlighter",
    "Marker",
    "Notebook",
    "Calendar",
    "Planner",
    "Wallet",
    "Keys",
    "Microwave",
    "Stove",
    "Fridge",
    "Freezer",
    "Sink",
    "Dishwasher",
    "Paper towel",
    "Dish soap",
    "Cutting board",
    "Pan",
    "Pot",
    "Rice cooker",
    "Blender",
    "Toaster",
    "Coffee maker",
    "Tea kettle",
    "Vacuum",
    "Mop",
    "Broom",
    "Bucket",
    "Sponges",
    "Cloth",
    "Trash bags",
    "Rubber bands",
    "Paperclips",
    "Sticky notes",
    "Post-it",
    "Index cards",
    "Printer",
    "Scanner",
    "Modem",
    "Router",
    "Wi-Fi",
    "Speaker",
    "Headphones",
    "Camera",
    "Flashlight",
    "Battery",
    "Power bank",
    "Extension cord",
    "Outlet",
    "Light bulb",
    "Coat",
    "Hat",
    "Scarf",
    "Gloves",
    "Socks",
    "Pants",
    "Shirt",
    "Shorts",
    "Underwear",
    "Belt",
    "Flip flops",
    "Slippers",
    "Blanket",
    "Rug",
    "Artwork",
    "Photo frame",
    "Book",
    "Magazine",
    "Newspaper",
    "Remote control",
    "Game console",
    "Television",
    "DVD player",
    "Streaming device",
    "Router",
    "Ethernet cable",
    "USB drive",
    "Cell phone case",
    "Screen protector",
    "Jewelry",
    "Bracelet",
    "Earrings",
    "Necklace",
    "Makeup",
    "Makeup brush",
    "Hair ties",
    "Safety pins",
    "First aid kit",
    "Medicine",
    "Vitamins",
    "Scale",
    "Yoga mat",
    "Dumbbells",
    "Exercise mat",
    "Water bottle",
    "Backpack",
    "Gym bag",
    "Cooler",
    "Snack container",
    "Picnic blanket",
    "Thermos",
    "Binoculars",
    "Map",
    "Compass",
    "Travel bag",
    "Luggage",
    "Suitcase",
    "Travel pillow",
    "Passport",
    "Travel adapter",
    "Guidebook",
    "Travel wallet",
    "Tickets",
    "Boarding pass",
    "Cash",
    "Change",
    "Credit card",
    "Debit card",
    "Gift card",
    "Membership card",
    "Loyalty card"


]
# Sports
sports_list = [
    "Soccer",
    "Basketball",
    "Baseball",
    "Tennis",
    "Golf",
    "Rugby",
    "Cricket",
    "Hockey",
    "Volleyball",
    "Swimming",
    "Running",
    "Cycling",
    "Boxing",
    "Wrestling",
    "Gymnastics",
    "Skiing",
    "Snowboarding",
    "Surfing",
    "Skateboarding",
    "Climbing",
    "Badminton",
    "Squash",
    "Handball",
    "Lacrosse",
    "Fencing",
    "Diving",
    "Rowing",
    "Canoeing",
    "Kayaking",
    "Racing",
    "Softball",
    "Triathlon",
    "Archery",
    "Bowling",
    "Billiards",
    "Darts",
    "Snooker",
    "Motorcycling",
    "Paintball",
    "Racquetball",
    "Cheerleading",
    "Powerlifting",
    "Bodybuilding"
]
# Colors
colors_list = [
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Black",
    "White",
    "Purple",
    "Orange",
    "Pink",
    "Brown",
    "Gray",
    "Teal",
    "Gold",
    "Silver",
    "Beige",
    "Coral",
    "Violet",
    "Indigo",
    "Magenta",
    "Cyan",
    "Turquoise",
    "Lavender",
    "Crimson",
    "Maroon",
    "Olive",
    "Peach",
    "Amber",
    "Mint",
    "Charcoal",
    "Azure",
    "Apricot",
    "Salmon",
    "Mahogany",
    "Plum",
    "Sapphire",
    "Ruby",
    "Emerald",
    "Periwinkle",
    "Topaz",
    "Onyx",
    "Jade",
    "Rust",
    "Mustard",
    "Slate",
    "Fuchsia",
    "Mulberry",
    "Sepia",
    "Almond",
    "Coffee",
    "Papaya",
    "Honey",
    "Chestnut",
    "Sand",
    "Lavender",
    "Berry",
    "Rose",
    "Night",
    "Seafoam",
    "Buff",
    "SlateBlue",
    "Crimson",
    "Orchid",
    "Caramel",
    "Tangerine"
]
